<?php

declare(strict_types=1);

namespace PHPSTORM_META {

    /**
     * PhpStorm metadata for Gacela framework
     * Auto-generated by generate:ide-helper command
     */

    // Container::get() and Gacela::get() autocomplete
    override(\Gacela\Framework\Container\Container::get(0), map([
        'Gacela\Console\ConsoleFacade' => \Gacela\Console\ConsoleFacade::class,
        'Gacela\Console\ConsoleFactory' => \Gacela\Console\ConsoleFactory::class,
        'Gacela\Console\ConsoleConfig' => \Gacela\Console\ConsoleConfig::class,
    ]));

    override(\Gacela\Framework\Gacela::get(0), map([
        'Gacela\Console\ConsoleFacade' => \Gacela\Console\ConsoleFacade::class,
        'Gacela\Console\ConsoleFactory' => \Gacela\Console\ConsoleFactory::class,
        'Gacela\Console\ConsoleConfig' => \Gacela\Console\ConsoleConfig::class,
    ]));

    // Facade method autocomplete
    // ConsoleFacade::getFactory() returns ConsoleFactory
    override(\Gacela\Console\ConsoleFacade::getFactory(0), type(\Gacela\Console\ConsoleFactory::class));

}
