#!/usr/bin/env php
<?php

declare(strict_types = 1);

use Gacela\CodeGenerator\CodeGeneratorFacade;
use Gacela\Framework\Config;

$slash = DIRECTORY_SEPARATOR;
$projectRootDir = getcwd() . $slash;
$autoloadPath = $projectRootDir . 'vendor' . $slash . 'autoload.php';

if (!file_exists($autoloadPath)) {
    exit("Cannot load composer's autoload file: " . $autoloadPath);
}

require $autoloadPath;

if ($argc <= 1) {
    exit(CodeGeneratorFacade::HELP_TEXT);
}

Config::setApplicationRootDir(realpath(__DIR__));

try {
    $codeGenerator = new CodeGeneratorFacade();
    $codeGenerator->runCommand($argv[1], array_slice($argv, 2));
} catch (Throwable $e) {
    print $e->getMessage() . PHP_EOL;
}
