#!/usr/bin/env php
<?php

declare(strict_types=1);

use Gacela\CodeGenerator\Infrastructure\Command\MakeFileCommand;
use Gacela\CodeGenerator\Infrastructure\Command\MakeModuleCommand;
use Gacela\Framework\Gacela;
use Symfony\Component\Console\Application;

$cwd = (string)getcwd();
if (!file_exists($autoloadPath = $cwd . '/vendor/autoload.php')) {
    exit("Cannot load composer's autoload file: " . $autoloadPath);
}

require $autoloadPath;

if (!class_exists(Application::class)) {
    $error = 'Cannot find class: %s. Did you forgot to require `%s` in your composer?';
    throw new RuntimeException(sprintf($error, Application::class, 'symfony/console:^5'));
}

Gacela::bootstrap($cwd);

$application = new Application();
$application->add(new MakeFileCommand());
$application->add(new MakeModuleCommand());
$application->run();

