#!/usr/bin/env php
<?php

declare(strict_types=1);

use Gacela\CodeGenerator\CodeGeneratorFacade;
use Gacela\CodeGenerator\Infrastructure\Command\MakeFileCommand;
use Gacela\CodeGenerator\Infrastructure\Command\MakeModuleCommand;
use Gacela\Framework\Gacela;
use Symfony\Component\Console\Application;

$cwd = getcwd();
if (!file_exists($autoloadPath = $cwd . '/vendor/autoload.php')) {
    exit("Cannot load composer's autoload file: " . $autoloadPath);
}

require $autoloadPath;

Gacela::bootstrap($cwd);

$codeGeneratorFacade = new CodeGeneratorFacade();

$application = new Application();
$application->add(new MakeFileCommand());
$application->add(new MakeModuleCommand());
$application->run();

