<?php

declare(strict_types=1);

namespace Gacela\Console\Domain\DtoGenerate;

use Gacela\Console\Domain\FileContent\PhpValue;

use Gacela\Framework\Dto\MissingDtoPropertyException;
use Gacela\Framework\Dto\Schema\DtoType;

use function implode;
use function sprintf;
use function strrpos;
use function substr;
use function ucfirst;

/**
 * Writes one declared shape as php source.
 *
 * A dedicated builder rather than a scaffolder stub: `FileContentGenerator`
 * substitutes three placeholders and cannot loop over properties. The output is
 * derived, not scaffolded -- nobody edits it afterwards, which is why the
 * command sits beside `cache:warm` rather than beside `make:file`.
 *
 * Byte-deterministic for one schema: properties arrive sorted, so regenerating
 * an unchanged declaration produces an identical file and leaves version
 * control quiet.
 */
final class DtoClassBuilder
{
    /**
     * @param array<string, DtoType> $properties
     */
    public function build(string $className, array $properties): string
    {
        $namespace = $this->namespaceOf($className);
        $shortName = $this->shortNameOf($className);

        $parts = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
        ];

        if ($namespace !== '') {
            $parts[] = 'namespace ' . $namespace . ';';
            $parts[] = '';
        }

        $parts[] = 'use ' . MissingDtoPropertyException::class . ';';
        $parts[] = '';
        $parts[] = '/**';
        $parts[] = ' * Generated by `vendor/bin/gacela dto:generate`. Do not edit -- regenerate it.';
        $parts[] = ' *';
        $parts[] = ' * Declared with `declareDtoSchema()`; every declarer of this shape contributes';
        $parts[] = ' * to it, so the properties below may come from more than one package.';
        $parts[] = ' */';
        $parts[] = 'final class ' . $shortName;
        $parts[] = '{';
        $parts[] = $this->constructor($properties);
        $parts[] = '';
        $parts[] = $this->fromArray($properties);

        foreach ($properties as $property => $type) {
            $parts[] = '';
            $parts[] = $this->getter($property, $type);
            $parts[] = '';
            $parts[] = $this->wither($property, $type, $properties);
        }

        $parts[] = '';
        $parts[] = $this->toArray($properties);
        $parts[] = '}';
        $parts[] = '';

        return implode("\n", $parts);
    }

    /**
     * @param array<string, DtoType> $properties
     */
    private function constructor(array $properties): string
    {
        $params = [];

        foreach ($properties as $property => $type) {
            // Every property is nullable on the way in, including the required
            // ones: `fromArray()` accepts a partial payload and the getter is
            // what refuses to answer. Rejecting at construction would make the
            // error name the array rather than the property nobody set.
            $params[] = sprintf('        private readonly ?%s $%s = null,', $type->phpType(), $property);
        }

        return "    private function __construct(\n" . implode("\n", $params) . "\n    ) {\n    }";
    }

    /**
     * @param array<string, DtoType> $properties
     */
    private function fromArray(array $properties): string
    {
        $args = [];

        foreach ($properties as $property => $type) {
            $args[] = sprintf(
                "            \$data['%s'] ?? %s,",
                $property,
                $type->hasDefault ? PhpValue::export($type->default) : 'null',
            );
        }

        return "    /**\n"
            . "     * @param array<string, mixed> \$data\n"
            . "     */\n"
            . "    public static function fromArray(array \$data): self\n"
            . "    {\n"
            . "        /** @psalm-suppress MixedArgument */\n"
            . "        return new self(\n"
            . implode("\n", $args) . "\n"
            . "        );\n"
            . '    }';
    }

    private function getter(string $property, DtoType $type): string
    {
        $method = 'get' . ucfirst($property);
        $doc = $type->description === ''
            ? ''
            : "    /**\n     * " . $type->description . "\n     */\n";

        if (!$type->isRequired) {
            return $doc . sprintf(
                "    public function %s(): ?%s\n    {\n        return \$this->%s;\n    }",
                $method,
                $type->phpType(),
                $property,
            );
        }

        // A required getter is non-nullable, which is the whole point of
        // declaring it required: the consumer writes no null check, and reading
        // one nothing set names the property rather than failing later on a
        // null somewhere else.
        return $doc . sprintf(
            "    public function %s(): %s\n    {\n        if (\$this->%s === null) {\n"
            . "            throw MissingDtoPropertyException::forProperty(self::class, '%s');\n"
            . "        }\n\n        return \$this->%s;\n    }",
            $method,
            $type->phpType(),
            $property,
            $property,
            $property,
        );
    }

    /**
     * @param array<string, DtoType> $properties
     */
    private function wither(string $property, DtoType $type, array $properties): string
    {
        $args = [];

        foreach ($properties as $other => $_type) {
            $args[] = sprintf('            %s,', $other === $property ? '$value' : '$this->' . $other);
        }

        return sprintf(
            "    public function with%s(?%s \$value): self\n    {\n        return new self(\n%s\n        );\n    }",
            ucfirst($property),
            $type->phpType(),
            implode("\n", $args),
        );
    }

    /**
     * @param array<string, DtoType> $properties
     */
    private function toArray(array $properties): string
    {
        $lines = [];

        foreach ($properties as $property => $_type) {
            // What was never set is omitted rather than written as null, so
            // fromArray($dto->toArray()) round-trips to the same instance.
            $lines[] = sprintf(
                "        if (\$this->%s !== null) {\n            \$data['%s'] = \$this->%s;\n        }",
                $property,
                $property,
                $property,
            );
        }

        return "    /**\n"
            . "     * @return array<string, mixed>\n"
            . "     */\n"
            . "    public function toArray(): array\n"
            . "    {\n"
            . "        \$data = [];\n\n"
            . implode("\n\n", $lines) . "\n\n"
            . "        return \$data;\n"
            . '    }';
    }

    private function namespaceOf(string $className): string
    {
        $position = strrpos($className, '\\');

        return $position === false ? '' : substr($className, 0, $position);
    }

    private function shortNameOf(string $className): string
    {
        $position = strrpos($className, '\\');

        return $position === false ? $className : substr($className, $position + 1);
    }
}
