<?php

declare(strict_types=1);

namespace GacelaTest\Feature\ReferenceApp\Invoicing\Billing\Domain;

use Gacela\Framework\Dto\MissingDtoPropertyException;

/**
 * Generated by `vendor/bin/gacela dto:generate`. Do not edit -- regenerate it.
 *
 * Declared with `declareDtoSchema()`; every declarer of this shape contributes
 * to it, so the properties below may come from more than one package.
 */
final class InvoiceRecord
{
    private function __construct(
        private readonly ?string $currency = null,
        private readonly ?string $customerReference = null,
        private readonly ?int $grossCents = null,
        private readonly ?string $issuedOn = null,
        private readonly ?int $netCents = null,
        private readonly ?string $number = null,
        private readonly ?int $taxCents = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        /** @psalm-suppress MixedArgument */
        return new self(
            $data['currency'] ?? null,
            $data['customerReference'] ?? null,
            $data['grossCents'] ?? null,
            $data['issuedOn'] ?? null,
            $data['netCents'] ?? null,
            $data['number'] ?? null,
            $data['taxCents'] ?? null,
        );
    }

    public function getCurrency(): string
    {
        if ($this->currency === null) {
            throw MissingDtoPropertyException::forProperty(self::class, 'currency');
        }

        return $this->currency;
    }

    public function withCurrency(?string $value): self
    {
        return new self(
            $value,
            $this->customerReference,
            $this->grossCents,
            $this->issuedOn,
            $this->netCents,
            $this->number,
            $this->taxCents,
        );
    }

    public function getCustomerReference(): string
    {
        if ($this->customerReference === null) {
            throw MissingDtoPropertyException::forProperty(self::class, 'customerReference');
        }

        return $this->customerReference;
    }

    public function withCustomerReference(?string $value): self
    {
        return new self(
            $this->currency,
            $value,
            $this->grossCents,
            $this->issuedOn,
            $this->netCents,
            $this->number,
            $this->taxCents,
        );
    }

    public function getGrossCents(): int
    {
        if ($this->grossCents === null) {
            throw MissingDtoPropertyException::forProperty(self::class, 'grossCents');
        }

        return $this->grossCents;
    }

    public function withGrossCents(?int $value): self
    {
        return new self(
            $this->currency,
            $this->customerReference,
            $value,
            $this->issuedOn,
            $this->netCents,
            $this->number,
            $this->taxCents,
        );
    }

    /**
     * YYYY-MM-DD
     */
    public function getIssuedOn(): string
    {
        if ($this->issuedOn === null) {
            throw MissingDtoPropertyException::forProperty(self::class, 'issuedOn');
        }

        return $this->issuedOn;
    }

    public function withIssuedOn(?string $value): self
    {
        return new self(
            $this->currency,
            $this->customerReference,
            $this->grossCents,
            $value,
            $this->netCents,
            $this->number,
            $this->taxCents,
        );
    }

    public function getNetCents(): int
    {
        if ($this->netCents === null) {
            throw MissingDtoPropertyException::forProperty(self::class, 'netCents');
        }

        return $this->netCents;
    }

    public function withNetCents(?int $value): self
    {
        return new self(
            $this->currency,
            $this->customerReference,
            $this->grossCents,
            $this->issuedOn,
            $value,
            $this->number,
            $this->taxCents,
        );
    }

    public function getNumber(): string
    {
        if ($this->number === null) {
            throw MissingDtoPropertyException::forProperty(self::class, 'number');
        }

        return $this->number;
    }

    public function withNumber(?string $value): self
    {
        return new self(
            $this->currency,
            $this->customerReference,
            $this->grossCents,
            $this->issuedOn,
            $this->netCents,
            $value,
            $this->taxCents,
        );
    }

    public function getTaxCents(): int
    {
        if ($this->taxCents === null) {
            throw MissingDtoPropertyException::forProperty(self::class, 'taxCents');
        }

        return $this->taxCents;
    }

    public function withTaxCents(?int $value): self
    {
        return new self(
            $this->currency,
            $this->customerReference,
            $this->grossCents,
            $this->issuedOn,
            $this->netCents,
            $this->number,
            $value,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $data = [];

        if ($this->currency !== null) {
            $data['currency'] = $this->currency;
        }

        if ($this->customerReference !== null) {
            $data['customerReference'] = $this->customerReference;
        }

        if ($this->grossCents !== null) {
            $data['grossCents'] = $this->grossCents;
        }

        if ($this->issuedOn !== null) {
            $data['issuedOn'] = $this->issuedOn;
        }

        if ($this->netCents !== null) {
            $data['netCents'] = $this->netCents;
        }

        if ($this->number !== null) {
            $data['number'] = $this->number;
        }

        if ($this->taxCents !== null) {
            $data['taxCents'] = $this->taxCents;
        }

        return $data;
    }
}
