<?php

declare(strict_types=1);

namespace Gacela\Console\Domain\ContainerCompiler;

use Gacela\Framework\Container\Container;

use function var_export;

final class ContainerCompiler
{
    public function compile(Container $container): string
    {
        $stats = $container->getStats();

        return $this->generatePhpCode($stats);
    }

    /**
     * @param array{
     *     registered_services: int,
     *     frozen_services: int,
     *     factory_services: int,
     *     bindings: int,
     *     cached_dependencies: int,
     *     memory_usage: string
     * } $stats
     */
    private function generatePhpCode(array $stats): string
    {
        $statsCode = var_export($stats, true);
        $timestamp = date('Y-m-d H:i:s');

        return <<<PHP
<?php

declare(strict_types=1);

/**
 * This file is auto-generated by container:compile command.
 * Generated at: {$timestamp}
 *
 * Container Statistics:
 * - Registered services: {$stats['registered_services']}
 * - Frozen services: {$stats['frozen_services']}
 * - Factory services: {$stats['factory_services']}
 * - Bindings: {$stats['bindings']}
 * - Cached dependencies: {$stats['cached_dependencies']}
 * - Memory usage: {$stats['memory_usage']}
 *
 * Note: This is a snapshot of container state at compilation time.
 * For full container optimization, consider using opcache preloading.
 */

return {$statsCode};

PHP;
    }
}
