<?php

declare(strict_types=1);

namespace Gacela\Console\Domain\IdeHelper;

use Gacela\Console\Domain\AllAppModules\AppModule;

use function implode;
use function sprintf;

final class IdeHelperGenerator
{
    /**
     * @param list<AppModule> $modules
     */
    public function generatePhpStormMeta(array $modules): string
    {
        $containerOverrides = $this->generateContainerOverrides($modules);
        $facadeOverrides = $this->generateFacadeOverrides($modules);

        return <<<PHP
<?php

declare(strict_types=1);

namespace PHPSTORM_META {

    /**
     * PhpStorm metadata for Gacela framework
     * Auto-generated by generate:ide-helper command
     */

    // Container::get() and Gacela::get() autocomplete
    override(\\Gacela\\Framework\\Container\\Container::get(0), map([
{$containerOverrides}
    ]));

    override(\\Gacela\\Framework\\Gacela::get(0), map([
{$containerOverrides}
    ]));

    // Facade method autocomplete
{$facadeOverrides}
}

PHP;
    }

    /**
     * @param list<AppModule> $modules
     */
    private function generateContainerOverrides(array $modules): string
    {
        $overrides = [];

        foreach ($modules as $module) {
            $facadeClass = $module->facadeClass();
            $overrides[] = sprintf("        '%s' => \\%s::class,", $facadeClass, $facadeClass);

            if ($module->factoryClass() !== null) {
                $factoryClass = $module->factoryClass();
                $overrides[] = sprintf("        '%s' => \\%s::class,", $factoryClass, $factoryClass);
            }

            if ($module->configClass() !== null) {
                $configClass = $module->configClass();
                $overrides[] = sprintf("        '%s' => \\%s::class,", $configClass, $configClass);
            }
        }

        return implode("\n", $overrides);
    }

    /**
     * @param list<AppModule> $modules
     */
    private function generateFacadeOverrides(array $modules): string
    {
        $overrides = [];

        foreach ($modules as $module) {
            $facadeClass = $module->facadeClass();

            if ($module->factoryClass() !== null) {
                $factoryClass = $module->factoryClass();
                $overrides[] = sprintf(
                    '    // %s::getFactory() returns %s',
                    $this->getShortClassName($facadeClass),
                    $this->getShortClassName($factoryClass),
                );
                $overrides[] = sprintf(
                    '    override(\\%s::getFactory(0), type(\\%s::class));',
                    $facadeClass,
                    $factoryClass,
                );
                $overrides[] = '';
            }
        }

        return implode("\n", $overrides);
    }

    /**
     * @param class-string $className
     */
    private function getShortClassName(string $className): string
    {
        $parts = explode('\\', $className);

        return end($parts) ?: $className;
    }
}
