<?php

declare(strict_types=1);

namespace Gacela\Console\Domain\IdeMeta;

use Gacela\Framework\AbstractFactory;

use function sprintf;
use function var_export;

/**
 * Renders the PhpStorm advanced-metadata file.
 *
 * The file is never executed, by PhpStorm or by anything else -- it is read as
 * source. That is why it carries no `declare(strict_types=1)` and why the ids
 * go through var_export(): they are arbitrary strings out of user code, and the
 * only guarantee that matters is that the result parses.
 */
final class MetaFileRenderer
{
    private const HEADER = <<<'PHP_WRAP'
    <?php
    
    // Generated by `vendor/bin/gacela ide:meta`. Do not edit -- regenerate it.
    //
    // Types `$this->getProvidedDependency(...)` inside a Factory, which the
    // editor otherwise reads as the `mixed` the signature declares.
    
    namespace PHPSTORM_META;
    
    PHP_WRAP;

    public function render(ProvidedDependencyMap $map): string
    {
        $lines = [
            self::HEADER,
            '',
            sprintf('override(\%s::getProvidedDependency(0), map([', AbstractFactory::class),
            // The wildcard: an id that names a class resolves to that class.
            // It is the whole of what both analysers type, it needs no scan to
            // know, and it stays right when a Provider changes.
            '    // An id that names a class or interface resolves to it.',
            "    '' => '@',",
        ];

        $entries = $map->entries();
        if ($entries !== []) {
            // Sorted so that regenerating an unchanged application produces a
            // byte-identical file: the doctor check compares content, and
            // discovery order is a directory listing, not a promise.
            ksort($entries);

            $lines[] = '    // String ids, typed by the #[Provides] method that registers each.';
            foreach ($entries as $id => $className) {
                $lines[] = sprintf('    %s => \%s::class,', var_export($id, true), $className);
            }
        }

        $lines[] = ']));';
        $lines[] = '';

        return implode("\n", $lines);
    }
}
