<?php

declare(strict_types=1);

namespace GacelaTest\Feature\ReferenceApp\Invoicing\Customer\Domain;

use Gacela\Framework\Attribute\PublicApi;
use Gacela\Framework\Dto\MissingDtoPropertyException;

/**
 * Generated by `vendor/bin/gacela dto:generate`. Do not edit -- regenerate it.
 *
 * Declared with `declareDtoSchema()`; every declarer of this shape contributes
 * to it, so the properties below may come from more than one package.
 */
#[PublicApi]
final class CustomerProfile
{
    private function __construct(
        private readonly ?string $countryCode = null,
        private readonly ?string $name = null,
        private readonly ?string $reference = null,
        private readonly ?string $taxId = null,
        private readonly ?string $tier = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): self
    {
        /** @psalm-suppress MixedArgument */
        return new self(
            $data['countryCode'] ?? null,
            $data['name'] ?? null,
            $data['reference'] ?? null,
            $data['taxId'] ?? null,
            $data['tier'] ?? 'standard',
        );
    }

    /**
     * ISO 3166-1 alpha-2
     */
    public function getCountryCode(): string
    {
        if ($this->countryCode === null) {
            throw MissingDtoPropertyException::forProperty(self::class, 'countryCode');
        }

        return $this->countryCode;
    }

    public function withCountryCode(?string $value): self
    {
        return new self(
            $value,
            $this->name,
            $this->reference,
            $this->taxId,
            $this->tier,
        );
    }

    public function getName(): string
    {
        if ($this->name === null) {
            throw MissingDtoPropertyException::forProperty(self::class, 'name');
        }

        return $this->name;
    }

    public function withName(?string $value): self
    {
        return new self(
            $this->countryCode,
            $value,
            $this->reference,
            $this->taxId,
            $this->tier,
        );
    }

    /**
     * the id a customer is billed under
     */
    public function getReference(): string
    {
        if ($this->reference === null) {
            throw MissingDtoPropertyException::forProperty(self::class, 'reference');
        }

        return $this->reference;
    }

    public function withReference(?string $value): self
    {
        return new self(
            $this->countryCode,
            $this->name,
            $value,
            $this->taxId,
            $this->tier,
        );
    }

    public function getTaxId(): ?string
    {
        return $this->taxId;
    }

    public function withTaxId(?string $value): self
    {
        return new self(
            $this->countryCode,
            $this->name,
            $this->reference,
            $value,
            $this->tier,
        );
    }

    public function getTier(): ?string
    {
        return $this->tier;
    }

    public function withTier(?string $value): self
    {
        return new self(
            $this->countryCode,
            $this->name,
            $this->reference,
            $this->taxId,
            $value,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $data = [];

        if ($this->countryCode !== null) {
            $data['countryCode'] = $this->countryCode;
        }

        if ($this->name !== null) {
            $data['name'] = $this->name;
        }

        if ($this->reference !== null) {
            $data['reference'] = $this->reference;
        }

        if ($this->taxId !== null) {
            $data['taxId'] = $this->taxId;
        }

        if ($this->tier !== null) {
            $data['tier'] = $this->tier;
        }

        return $data;
    }
}
