<?php

declare(strict_types=1);

/**
 * This file is auto-generated by container:compile command.
 * Generated at: 2026-02-10 11:16:12
 *
 * Container Statistics:
 * - Registered services: 0
 * - Frozen services: 0
 * - Factory services: 0
 * - Bindings: 0
 * - Cached dependencies: 0
 * - Memory usage: 8 MB
 *
 * Note: This is a snapshot of container state at compilation time.
 * For full container optimization, consider using opcache preloading.
 */

return array (
  'registered_services' => 0,
  'frozen_services' => 0,
  'factory_services' => 0,
  'bindings' => 0,
  'cached_dependencies' => 0,
  'memory_usage' => '8 MB',
);
